// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceOrderManagement.Infrastructure.Data;

#nullable disable

namespace ServiceOrdersManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ServiceOrdersManagement.Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("ServiceOrdersManagement.Domain.Entities.ServiceOrder", b =>
                {
                    b.OwnsOne("ServiceOrdersManagement.Domain.Entities.Client", "Client", b1 =>
                        {
                            b1.Property<int>("ServiceOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Document")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientDocument");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientPhone");

                            b1.HasKey("ServiceOrderId");

                            b1.ToTable("ServiceOrders");

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.Navigation("Client")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
